cache:
    directories:
        - vendor

language: php

php:
    - 7.2

matrix:
    fast_finish: true

before_install:
    - sudo apt-get install -y imagemagick
    - yes '' | pecl install imagick
    - composer install

script: ./vendor/bin/phpunit
