cache:
    directories:
        - vendor

language: php

php:
    - 7.2

matrix:
    fast_finish: true

before_install:
    - apt-get install -y imagemagick
    - pecl install imagick
    - pecl install redis
    - composer install

script: ./vendor/bin/phpunit
